# Generated by Django 4.0.4 on 2022-05-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.availability'),
            preserve_default=False,
        ),
    ]
