# Generated by Django 4.0.4 on 2022-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_availability_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.ManyToManyField(to='product.availability'),
        ),
    ]
