# Generated by Django 4.0.4 on 2022-05-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_availability_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
